### ISSUE TITLE
Issueベースの開発　レビュー依頼

### ISSUE THREAD

**Issue by TomitaHayato** [TomitaHayato/portfolio#5]
## projectsへのリンク
https://github.com/users/TomitaHayato/projects/1
## 実装予定の機能
* [ ] ユーザーの新規登録
* [ ] ユーザープロフィール編集
* [ ] ユーザープロフィール詳細
* [ ] ユーザーアイコン作成
* [ ] ユーザーログイン・ログアウト
* [ ] お試しログイン
* [ ] トップページ
* [ ] マイページ
* [ ] ルーティン作成・編集・削除機能
* [ ] 自分のルーティン一覧機能
* [ ] タスク作成・編集・削除機能
* [ ] タスクの順番を保存する機能
* [ ] タスクの順番をドラッグ&ドロップで編集できる機能
* [ ] 実践するルーティンを選ぶ機能
* [ ] 実践しているルーティンに含まれるタスクを順番に表示する機能
* [ ] タスクにタグをつける機能
* [ ] パスワードリセット機能
* [ ] ルーティン投稿機能
* [ ] 投稿一覧機能
* [ ] 投稿されたルーティンをコピーできる機能
* [ ] rspecを使用したテスト
* [ ] rubocopを使用したLintチェック
## 必要なページ
* [ ] ログイン前ヘッダー
* [ ] ログイン後ヘッダー
* [ ] トップページ
* [ ] ユーザー新規登録フォーム
* [ ] ユーザーログインフォーム
* [ ] ユーザープロフィール詳細
* [ ] ユーザープロフィール編集フォーム
* [ ] マイページ
* [ ] ルーティン作成フォーム
* [ ] ルーティン編集フォーム
* [ ] 作成したルーティン一覧画面
* [ ] ルーティン詳細画面
* [ ] タスク作成フォーム
* [ ] タスク編集フォーム
* [ ] タスク遂行画面
* [ ] ルーティン達成画面
* [ ] 利用規約・プライバシーポリシー画面
* [ ] パスワードリセット画面
* [ ] パスワードリセット用メール送信完了画面
* [ ] パスワードリセットフォーム

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
ユーザー新規登録機能（View,  バリデーション, デザイン調整）のissueにストーリーポイントが記載されていなかったのでご確認をお願いします。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/9a9491ef9071ef82c409c0eae70adbc9.png)](https://startup-technology.gyazo.com/9a9491ef9071ef82c409c0eae70adbc9)

また、ストーリーポイント8のissueは再度見直していただき、1つのissueが5以下になるように分解してください。
（例：調査、ロジック、viewそれぞれのissueに分けるなど）

**Comment by TomitaHayato** [comment]
レビューありがとうございます。こちらの確認不足で失礼いたしました。
issueのストーリーポイントが全て5以下になるように修正いたしました。
ご確認よろしくお願いいたします。


## projectsへのリンク
https://github.com/users/TomitaHayato/projects/1

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
概ね良いかと思います。LGTMです。

---

以下MVP後でも良いかと思ったものになります。
- パスワードリセット
- ドラッグ＆ドロップ
- 画像アップロード
- 利用規約・プライバシーポリシー
- マイページ
- GitHub Actions
- RSpec
- Rubocop

**Comment by syuuarsaga** [comment]
ご確認ありがとうございます！
引き続きMVPリリースに向けて開発頑張ってください。

**Comment by TomitaHayato** [comment]
ご確認ありがとうございました。
