### ISSUE TITLE
8/29 MVPレビュー依頼

### ISSUE THREAD

**Issue by TomitaHayato** [TomitaHayato/portfolio#72]
## 各種情報
- サービス名：「Morning Forest」
- サービスURL： https://morning-routine-hub-0de86cb64827.herokuapp.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
* [x] ユーザーの新規登録・ログイン機能
* [x] トップページ
* [x] 作成したルーティン一覧機能
* [x] マイページ（ルーティン開始機能）
* [x] ルーティン遂行機能(タスクを順に達成していく機能) 
* [x] ルーティン投稿機能
* [x] 投稿をコピーする機能
* [x] ページネーション

## READMEレビュー時から変更した機能
- 実装しなかった機能
  - 新規登録なしでも一部の機能が使えるお試しログイン機能
  - 通知機能

## サービスイメージがわかるようなスクリーンショット等
<ul>
  <li>
    <h3>ルーティンを作成する</h3>
    <img src="https://i.gyazo.com/b8bf359de697ee6e34624ca09427127f.jpg" width="480">
  </li>

  <li>
    <h3>ルーティンにタスクを追加する</h3>
    <img src="https://i.gyazo.com/35a9ab7a7d8e25b967a21bdc10d10637.jpg" width="480">
  </li>

  <li>
    <h3>ルーティンを実践する</h3>
    <p>ルーティン一覧画面から「実践する」ボタンを押してマイページへ遷移します。</p>
    <p>マイページの「スタート」ボタンを押すとタスクが開始されます。</p>
    <img src="https://i.gyazo.com/8499e5aaf6f72caf36fa1380739cd2ca.jpg"  width="480">
  </li>

  <li>
    <h3>ルーティンを投稿する（GIF）</h3>
    <p>ルーティン一覧画面の「投稿する」ボタンを押してルーティンを投稿します。
    <img src="https://i.gyazo.com/ab63fb8b9dce99586c7513d483ad4c51.gif" alt="ルーティンを投稿する操作動画" width="480">
  </li>

</ul>

**Comment by TomitaHayato** [comment]
提出が遅れてしまい申し訳ございません。

**Comment by TakenakaEri** [comment]
ありがとうございます！

> ルーティンを実践する
> ルーティン一覧画面から「実践する」ボタンを押してマイページへ遷移します。
> 
> マイページの「スタート」ボタンを押すとタスクが開始されます。

上記の項目で、スタートボタンを押すと以下のようなエラーが出ました。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/77f9c408be6807f2ad3efdf9a861287e.png)](https://startup-technology.gyazo.com/77f9c408be6807f2ad3efdf9a861287e)

対応をお願いできますでしょうか？

**Comment by TomitaHayato** [comment]
レビューありがとうございます！

上記のエラーを修正しました。
ご確認よろしくお願いいたします。

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
